### ISSUE TITLE
Filters break with certain fields

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/redhen#41]
File fields break the redhen contact filter:
https://www.drupal.org/node/2203959

So do addressfields in some quirky ways, and a bunch of other fields. Possible resolutions:
1. Build a list of allowed field-types and leverage it in redhen_filter_form_fields() to restrict what fields we add to this form. Could allow a hook to alter the list.
2. Create a UI for disabling/enabling fields on the filtration pages. Seems like this is worse that just letting people use Views.
3. Build a default Views instance of the admin page and retire the admin page.

Other thoughts?
@tauno @levelos @bleeDev

**Comment by levelos** [comment]
What about injecting a setting into the field edit form for a fields
attached to contact or org bundles and then storing a single serialized
array on which fields to exclude? Or alternatively at the bundle settings
page?

I think the solution needs to be configurable to since fields, and field
types, are added through configuration. It would be very difficult to
exclude a field from filtering if you have to implement a hook in code
after adding the field through the UI or features.

I don't want to be dogmatic about adding Views, but it would be a major
change at this point. I'm open to discussing ...

**Comment by tauno** [comment]
I think the setting on the field config makes sense. We've discussed a
similar feature for determining which contact fields show up on the user
registration form.

I think we're still less than 50% with our clients needing to overwrite the
default listings with Views, but that's largely due to the use of
Salesforce where clients like LAC don't really ever use redhen listings.
