### ISSUE TITLE
Increase Org Name 50 Char limit

### ISSUE THREAD

**Issue by arosboro** [thinkshout/redhen#82]
I've been hitting this limit often.  I feel it makes more sense not to limit the name and allow a more typical 255 characters for the name.

Client has a requirement that the name as closely as possible matches the official registered name of the organization.

**Comment by alexellison** [comment]
@unclegcb when `redhen_org_update_8101` defined in this merge is run on a DB with existing Orgs it fails with the following error:
```
Drupal\Core\Entity\Exception\FieldStorageDefinitionUpdateForbiddenException: The SQL storage cannot change the  [error]
schema for an existing field (name in redhen_org entity) with data. in
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->updateSharedTableSchema() (line 1403 of
/Users/AlexEllison/Sites/teaching-tolerance/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorageSchema.php).
```

Reopening to fix before we roll the next release.

**Comment by unclegcb** [comment]
@arosboro have you run in to this issue or were you operating on an empty DB?

**Comment by arosboro** [comment]
I was operating off of a set of data from a migration sourced from csv, but I may have rolled back before applying the update.  I will re-install/devel generate content in a few days to see if I can reproduce the issue @caxy4 is having.

**Comment by arosboro** [comment]
@unclegcb Ok sorry for the delay.  I've had some time to look at this and found the issue see the above mentioned PR

**Comment by nrackleff** [comment]
I applied the patch on a local site that had data and all the names of the redhen_orgs were deleted and left null. Rebuilding now and debugging to see what might have happened.

**Comment by nrackleff** [comment]
I have experienced spotty results with this patch. The first time I ran it in a local development environment it wiped out the org names in my database. The code looked solid and I could see no reason for the failure, so I refreshed the database and ran it again and it worked the second time. A week or so later, I pushed the code with this patch to a Pantheon dev environment and the same thing happened. The org names were all deleted from the database.

**Comment by arosboro** [comment]
Hi Nancy,


The code changes the structure of the of the Org name field.  It needs to be applied from the start, otherwise, you'll see data loss which you are experiencing.  I'll have to see about writing a migration because I was thinking this was going to be included in RedHen several months ago, mitigating the issue for new installations.


We're about to get back into regular development on a project utilizing RedHen, which had been on hold.  So I should have availability to work on this issue before too long.  I'll run through some scenarios to see if I can make the patch more reliable.


Sorry for the difficulty this has been causing you; I know it can be frustrating to have to resort to restoring backups.


________________________________

**Comment by nrackleff** [comment]
@arosboro Thank you for your quick response. So this patch https://github.com/thinkshout/redhen/commit/cc1b910e78c4228e042f7d180d738899c8dc495c.patch will not work against a site that already has data? It looks like it should work.

**Comment by arosboro** [comment]
My intent was to keep a copy of the names to restore after the schema update.  It's possible the order of the update hooks is wrong, or they need to be combined to work properly.
________________________________

**Comment by nrackleff** [comment]
@arosboro I worked with @unclegcb this morning and we came up with a patch based on something we did on a client site, which was partially based on http://www.jpstacey.info/blog/2017-07-21/altering-length-drupal-8-text-field-contains-data. This patch will work against the alpha-3 release. I am having to upload it as a text file since I can't upload .patch here. 
[redhen_org-update-org-name-length-db-and-schema.txt](https://github.com/thinkshout/redhen/files/2073360/redhen_org-update-org-name-length-db-and-schema.txt)

**Comment by nrackleff** [comment]
Created an issue on drupal.org as well. https://www.drupal.org/project/redhen/issues/2977588

**Comment by unclegcb** [comment]
@arosboro FYI, Nancy and I looked at this today and found a way to bypass Drupal's update manager and it's insistence that you have no field values. This allows us to just change the structure with all the data in-place, which feels a lot safer:

https://www.drupal.org/node/2977588

This is adapted from a similar trick for fields that we have used before, which can be found here:
http://www.jpstacey.info/blog/2017-07-21/altering-length-drupal-8-text-field-contains-data

Just in case you were curious about how this turned out!

**Comment by arosboro** [comment]
@unclegcb @nrackleff Thanks for the update, and insight into how the solution was arrived upon.   It looks like this issue can be closed then.  I see the same update numbering was used, so this won't negatively affect anybody who had been using the previous patch.
